### ISSUE TITLE
make报错

### ISSUE THREAD

**Issue by LZLGitHubs** [NingLeixueR/ngl#1]
大佬你好，我把你这个项目拉下来的时候，我在ubantu环境下把这些第三方库都安装了，并根据我自己的目录重新配置 了这个set(CMAKE_CXX_FLAGS "${COLLECT_GCC} -std=c++20 -march=native -msse4.1 -O3 -lrt -L/usr/lib64/mysql/ -lcurl -L/usr/lib64/ -L/usr/lib64/protocol -L`pwd`/../../../lib -I/usr/include/mysql -I/usr/include/curl -I/usr/include/x86_64-linux-gnu/curl -L/usr/lib/x86_64-linux-gnu/ -I/usr/include -I/usr/include/protobuf -L/usr/local/lib/ -I/usr/local/include -I/usr/local/include/google/protobuf -lmysqlclient")
但是make的时候很多报错，我觉得是我的第三方库下载有问题，能否问一下大佬可以给出一些详细的第三库的安装步骤嘛，冒昧打扰了

**Comment by NingLeixueR** [comment]
github actions有整个编译过程，https://github.com/NingLeixueR/ngl/blob/main/.github/workflows/cmake-unbutu.yml
